ntp:
    resource: "@NTPBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

logout:
    path: /logout
    
paragon_upload:
    path : /uploadparagon
    defaults:
        _controller: NTPBundle:File:uploadFile
        dataset: "Paragon"

file_display:
    path : /filedisplay
    defaults:
        _controller: NTPBundle:File:displayFiles

upload_plan_display:
    path : /uploadedplans
    defaults:
        _controller: NTPBundle:File:uploadedPlans
        
process_csv:
    path : /processcsv/{id}
    defaults:
        _controller: NTPBundle:File:processCsv

delete_csv:
    path : /deletecsv/{id}
    defaults:
        _controller: NTPBundle:File:deleteCsv

download_file:
    path : /downloadfile
    defaults:
        _controller: NTPBundle:File:downloadFile

dashboard_report:
    path : /report/dashboard
    defaults:
        _controller: NTPBundle:Report:dashboard    
        
tractor_report:
    path : /report/tractors
    defaults:
        _controller: NTPBundle:Report:tractorReport

storeseta_report:
    path : /report/storeseta
    defaults:
        _controller: NTPBundle:Report:storesETA


paragon_run_sheets_report:
    path : /report/paragonrunsheets
    defaults:
        _controller: NTPBundle:Report:paragonRunSheetReport
     
tms_route_dispaly:
    path : /tms/routedisplay
    defaults:
        _controller: NTPBundle:TMS:routeDisplay


summary_volume_report:
    path : /report/volumereport
    defaults:
        _controller: NTPBundle:Report:summaryVolume


wickesDashboard_report:
    path : /wickesreport/dashboard
    defaults:
        _controller: NTPBundle:WickesReport:wickesDashboard

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

delete_plan:
    path : /deleteplan
    defaults:
        _controller: NTPBundle:File:deletePlan

manual_email_trigger:
    path : /manualemialtrigger
    defaults:
        _controller: NTPBundle:ReportAdmin:manualEmailTrigger    