ntp:
    resource: "@NTPBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

logout:
    path: /logout
    
paragon_upload:
    path : /uploadparagon
    defaults:
        _controller: NTPBundle:File:uploadFile
        dataset: "Paragon"

process_CSV:
    path : /processcsv
    defaults:
        _controller: NTPBundle:ProcessFile:importCSV