ntp:
    resource: "@NTPBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

logout:
    path: /logout
    
paragon_upload:
    path : /uploadparagon
    defaults:
        _controller: NTPBundle:File:uploadFile
        dataset: "Paragon"

file_display:
    path : /filedisplay
    defaults:
        _controller: NTPBundle:File:displayFiles
        
process_csv:
    path : /processcsv/{id}
    defaults:
        _controller: NTPBundle:File:processCsv

dashboard_report:
    path : /report/dashboard
    defaults:
        _controller: NTPBundle:Report:dashboard
     
    