# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    web_path: 'C:\wamp\www\data'

services:
    fileprocessor.csvfilewriter:
        class: NTPBundle\FileProcessor\CsvFileWriter
        arguments: ['@doctrine.orm.entity_manager']

    fos_user.doctrine_registry:
        alias: doctrine
        
    ntp.form.registration:
        class: NTPBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: ntp_user_registration }
            
    app.custom_mailer:
        class:     NTPBundle\Mailer\CustomMailer
        arguments: ['@logger']