# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    web_path: 'C:\wamp\www\data'

services:
    fileprocessor.csvfilewriter:
        class: NTPBundle\FileProcessor\CsvFileWriter
        arguments: ['@request_stack']

    fos_user.doctrine_registry:
        alias: doctrine