services:
#    ntp.csvwriter:
#        class: NTPBundle\FileProcessor\csvWriter
#        arguments: [ @doctrine.orm.entity_manager  ]

    paragonreports:
        class: NTPBundle\Reports\ParagonReports
        arguments: [ '@doctrine.orm.entity_manager'  ]